osx_image: xcode11
language: objective-c
cache: cocoapods
xcode_workspace: Example/KLAlertController.xcworkspace
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

script:
- set -o pipefail

- xcodebuild build -workspace Example/KLAlertController.xcworkspace -scheme KLAlertController-Example -destination 'platform=iOS Simulator,name=iPhone 11 Pro' -configuration Debug CODE_SIGNING_ALLOWED=NO | xcpretty -c

#- pod lib lint --verbose
